


export const cuisines = [
    'Afghan',
    'African',
    'American',
    'Andhra',
    'Arab',
    'Asian',
    'Assamese',
    'Awadhi',
    'Bangladeshi',
    'Bengali Recipes',
    'Bihari',
    'British',
    'Burmese',
    'Cantonese',
    'Caribbean',
    'Chettinad',
    'Chinese',
    'Coastal Karnataka',
    'Continental',
    'Coorg',
    'European',
    'French',
    'Fusion',
    'Goan Recipes',
    'Greek',
    'Gujarati Recipes',
    'Haryana',
    'Himachal',
    'Hunan',
    'Hyderabadi',
    'Indian',
    'Indo Chinese',
    'Indonesian',
    'Italian Recipes',
    'Japanese',
    'Jewish',
    'Jharkhand',
    'Karnataka',
    'Karnataka Coastal',
    'Kashmiri',
    'Kerala Recipes',
    'Kongunadu',
    'Konkan',
    'Korean',
    'Lucknowi',
    'Maharashtrian Recipes',
    'Malabar',
    'Malaysian',
    'Malvani',
    'Mangalorean',
    'Mediterranean',
    'Mexican',
    'Middle Eastern',
    'Mughlai',
    'Nagaland',
    'Nepalese',
    'North East India Recipes',
    'North Indian Recipes',
    'North Karnataka',
    'Oriya Recipes',
    'Pakistani',
    'Parsi Recipes',
    'Punjabi',
    'Rajasthani',
    'Shandong',
    'Sichuan',
    'Sindhi',
    'Singapore',
    'South Indian Recipes',
    'South Karnataka',
    'Sri Lanka',
    'Sri Lankan',
    'Swedish',
    'Tamil Nadu',
    'Thai',
    'Udupi',
    'Uttar Pradesh',
    'Uttarakhand - North Kumaon',
    'Vietnamese',
];